#!/bin/bash

if [ $1 = "help" ]; then
		echo ""
		echo "THIS IS A STATIC HELP OUTPUT - Real script could could have changed since this snapshot."
		echo ""
		echo "Script Arguments:"
		echo "    run"
		echo "    clean"
		echo "    help"
		echo ""
		./waf --run "coap --PrintHelp"
		exit

elif [ $1 = "clean" ]; then
    echo Removing stored .zip files
    ls *.zip
    rm *.zip
    rm energy_*
    rm *.pcap
    rm coap_trace.tr
    rm coap_animation.xml
    rm state_*
    rm routetables
    rm output.log

else
  echo removing old trace files
  rm energy_*
  rm *.pcap
  rm coap_trace.tr
  rm coap_animation.xml
  rm state_*
  rm routetables
  rm output.log
  echo Starting simulation:
  a="$(echo "$*" | tr ' ' _ | tr = _ | tr -d -)"
  b="$(date +%s)"
  c="_"
  echo Arguments: $*
  ./waf --run "coap $*" &> output.log
  echo Done
  d="$a$c$b".zip
  echo "Copying animation"
  cp coap_animation.xml tempanim.xml
  echo Compressing simulation to $d
  zip $d energy_*
  rm coap_trace.tr
  rm coap_animation.xml
  zip -u $d output.log
  zip -u $d *.pcap
  #zip -u $d coap_trace.tr
  #zip -u $d coap_animation.xml
  zip -u $d *_cache
  zip -u $d state_*
  zip -u $d scratch/coap.cc
  zip -u $d routetables
  echo Done
  echo Removing files
  rm energy_*
  rm *.pcap
  #rm coap_trace.tr
  #rm coap_animation.xml
  rm state_*
  rm routetables
  rm *_cache
  #tail -10 output.log
  #rm output.log
  du -h $d
  #../netanim-3.107/NetAnim &
fi

